config/routes.rb
Hero::Application.routes.draw do
  devise_for :users

  resources :questions do
  	resources :comments
    
    collection do
      get 'about'
    end
  end

  root :to => 'questions#index'
  resources :users, :only => ["show"]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :user_id, :body, :question_id

  delegate :username, :to => :user, 		:prefix => :true, :allow_nil => :true
  delegate :title,    :to => :question, :prefix => :true, :allow_nil => :true

  belongs_to :user, :foreign_key => :user_id
  belongs_to :question, :foreign_key => :question_id
  
  validates :body, :presence => true
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :body, :date, :title, :user_id

  delegate :username,    :to => :user, :prefix => true, :allow_nil => true

  has_many :comments
  belongs_to :user, :foreign_key => :user_id

  validates :body,  :presence => true
  validates :title, :presence => true

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me

  has_many :questions, :dependent => :destroy
  has_many :comments, :through => :questions, :dependent => :destroy
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :authenticate_user!

  def create
   @question = Question.find(params[:question_id])
 	 @comment = @question.comments.new(params[:comment])
 	 @comment.user_id = current_user.id

 	 if @comment.save
 	 	redirect_to question_path(@question)
 	 else
 	 	
 	 end
  end

  def edit
  	@comment = Comment.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])
    @question.update_attribute(:count, @question.count + 1)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = current_user.questions.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = current_user.questions.new(params[:question])
    @question.count = 0

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = current_user.questions.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = current_user.question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
  def about
    
  end
  
  

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!

	def show
		@user = current_user 
		#User.find(params[:id])
		#will also be fine
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p>
  <b>Comment:</b>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               :confirm => 'Are you sure?',
               :method => :delete %>
</p>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/layouts/application.html.erb
<html>
<head>
  <title>Hero</title>
  <%= stylesheet_link_tag    :application, :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= @question.user_username %><br />
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/about.html.erb
<html>
	<head id="about">
		<title>About</title>
	</head>

	<body>
		<h1>About the Site</h1>
		<pre class="yellow">
			that could be the <strong>Worst</strong> website you've ever seen
				 but I finally decided to put this version
				   	cuz it's we that will make it better , everyday :-)
		</pre>
		<pre class="green">
			And this ugly UI is to mention you 
			    We always have something to do

			While contrasting to the Home Page the css that I copied from the other site
					We know we are still far, but never mind that
		</pre>
		<footer id="link"><%= link_to "Home", root_path %></footer>
	</body>
	<%= yield %>
</html>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %>|
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<html>
  <head>
    <title>HeroStands Version0.03</title>
    <%= stylesheet_link_tag :application %>
    <%= csrf_meta_tag %>
    <%= javascript_include_tag :defaults %>
  </head>

  <body>
    <header id="page_header">
      <nav id="nav_user">
        <ul>
          <% if user_signed_in? %> 
            <li><span id="currentuser"><%= link_to(current_user.username||current_user.email, user_path(current_user)) %></span></li>
            &nbsp;
            <li><%= link_to "My Profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
          <% else %> 
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>

      <div id="page_title">
        <h1>Write  down what confusing you</h1>
        <h2>Fast <span>changing</span> 24-7 <span>Version 0.03</span></h2>
      </div>
    </header>

    <header id="nav_header">
      <nav id="nav_main">
        <ul>
          <li><%= link_to "questions", root_path %></li>
          <li><%= link_to "about", about_questions_path %></li>
        </ul>
      </nav>
    </header>

    <section id="maincontainer">
      <section id="content">
        <section id="flash">
          <% @questions.each do |question| %>
            <article class="article">
              <div class="title"><%= link_to question.title,  question_path(question) %></div>
              <% if question.user_username %>
                <div class="username"><%= question.user_username %></div>
              <% else %>
                <div class="username"><%= question.user_id %></div>
              <% end %>
            </article>
          <% end %>
          <br>
              <% if user_signed_in? %>
                <%= link_to 'New Question', new_question_path %>
              <% end %>
        </section>

        <%= yield %>
      </section>

      <section id="sidebar">
        <section id="go" class="box">
          <h3>What gonna do next step</h3>
          <ul>
            <li>User system</li>
            <li>Ranking</li>
            <li>Comments</li>
            <li>Views</li>
          </ul>
        </section>
      </section>
    </section>

    <footer id="page_footer">
      <h3>Let's make it better</h3>
    </footer>
  </body>
</html>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>
<%= @question.count %>
<p>
  <b>User:</b>
  <%= @question.user_username || @question.user_id %>
</p>

<p>
  <b>Title:</b>
  <%= @question.title %>
</p>

<p>
  <b>Body:</b>
  <%= @question.body %>
</p>

  <b>Date:</b>
  <%= @question.date %>
</p>

<% if user_signed_in? && current_user == @question.user %>
<%= link_to 'Edit', edit_question_path(@question) %>|
<% end %>

<%= link_to 'Back', questions_path %>

<h5>Comments:</h5>
<% @question.comments.each do |comment| %>

  <p>
    <b>Comment :</b>
    <%= comment.body %>
  </p>
<% end %>
<br>
<h5>Add a comment:</h5>
<%= form_for([@question, @question.comments.build]) do |f| %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= link_to 'Show', tag %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>

app/views/users/show.html.erb
<%= @user.username %> <br> <hr>
<% @user.questions.each do |q| %>
	questions: <%= q.title %> <br>
	details : <%= q.body %> <br>
	<hr>
<% end %>